### ISSUE TITLE
Class list disappeared and extension choice

### ISSUE THREAD

**Issue by mauriva** [al-caughey/Google-Meet-Attendance#6] opened 2020-04-22 14:56 UTC
After a silent update, this afternoon the Chrome extension no longer shows the list of classes I added.
There is no longer the combo to select the class nor the item to add a new one.

I also take this opportunity to ask for an addition to the software.
I downloaded this morning the attendance list. I found the file with the .csv extension, but opening it with the latest version of Excel, the file is not correctly recognized, especially the character that indicates the presence of a student.
The same file opened with NotePad instead is perfectly legible: the fact is that the csv files on my PC are associated with Excel ...
The .txt file downloaded before the last update instead opened without display problems.
I wanted to ask therefore to be able to set the extension with which the file is downloaded.

**Comment by Eagle-Man** [comment] 2020-04-22 16:28
I think I noticed the same thing.  The combo box is technically there, but the arrow is not, the list is clipped, and the box is too small (see attached image).  It seems that the entire extension loads correctly initially - I can see it for a second - but once the load is complete, it resizes and all the class-based stuff is clipped so that it is unusable.
![image](https://user-images.githubusercontent.com/53746675/80007566-4283d000-847b-11ea-8900-83d34cc3e27c.png)

**Comment by al-caughey** [comment] 2020-04-22 22:23
I've not notice that at my end but someone else did too... for them, the problem went away when they cleared the browser history. Because that fixed it, I'm guessing that they probably had to just clear the localStorage variables...  Like I said, I cannot reproduce it here but I'm guessing maybe just the `Current-Class-Code` key
If not that one, blast them all

**Comment by al-caughey** [comment] 2020-04-22 22:33
I can replicate the  checkmark problem in the CSV if the import character set is not UTF-8 (which it is set to in when the file blob is created. (line 102)

A quick(er) way to solve the problem might be to replace the check mark with another character or perhaps a time stamp for when they first arrived in the meet
I'm not sure if this'll help: https://stackoverflow.com/questions/42462764/javascript-export-csv-encoding-utf-8-issue

**Comment by Eagle-Man** [comment] 2020-04-23 00:14
Yes, I believe clearing the Current-Class-Code did the trick.  I tried deleting the localstorage cookies from the security menu beside the URL, but that didn't work.  When I went in through the developer console and deleted that key, I think that worked.  I also disabled, refreshed, and then reenabled the extension after that.

**Comment by Eagle-Man** [comment] 2020-04-23 17:22
> After a silent update, this afternoon the Chrome extension no longer shows the list of classes I added.
> There is no longer the combo to select the class nor the item to add a new one.
> 
> I also take this opportunity to ask for an addition to the software.
> I downloaded this morning the attendance list. I found the file with the .csv extension, but opening it with the latest version of Excel, the file is not correctly recognized, especially the character that indicates the presence of a student.
> The same file opened with NotePad instead is perfectly legible: the fact is that the csv files on my PC are associated with Excel ...
> The .txt file downloaded before the last update instead opened without display problems.
> I wanted to ask therefore to be able to set the extension with which the file is downloaded.

@mauriva - As a .csv file, you cannot simply open it in Excel, it must be imported as a data source with UTF-8 as the code page and Tab as the delimiter.

For ribbon-style versions of Excel, try the instructions [here](https://www.itg.ias.edu/content/how-import-csv-file-uses-utf-8-character-encoding-0).
For menu-style versions of Excel, try the instructions [here](https://stackoverflow.com/questions/6002256/is-it-possible-to-force-excel-recognize-utf-8-csv-files-automatically/6488070#6488070) (the marked solution)

**Comment by mauriva** [comment] 2020-04-24 06:58
Clear the browser history doesn't work on my side. Also delete the Current-Class-Code value doesn't help. 
The combo for the class list is still missing, so I can no longer add, remove, select classes.

for the csv file. As far as I'm concerned, I have no problems managing it: I can open it both with a text editor and with Excel.
My suggestion depends on the fact that I have colleagues who would not be able to open that file easily: having the possibility to open it as a simple text file makes it easier for someone ...

**Comment by Eagle-Man** [comment] 2020-04-24 19:51
Did you try uninstalling and reinstalling it after deleting Current-Class-Code through the developer console?  That worked for me and I haven't had that problem since.

**Comment by mauriva** [comment] 2020-04-25 07:34
Trying to uninstall and reinstall, after manual deleting Curret-Class-Code doesn't work for me.
When Meet opens, it seems that the extension windows is correct, but after a split second it shrinks, as if the class list combo was present at first and then hidden.

**Comment by al-caughey** [comment] 2020-04-25 22:10
I've tidied up the code relating to the drop down list, I think it is good now.  I've also add a reset option to the drop down that clears the LS variables (or most of them.)

I've also fixed the UTF-8 complaint... 

So marking as closed

**Closed by al-caughey** 2020-04-25 22:10 UTC
